#!/bin/bash
# ESP-ADF 安装脚本
# 由于网络问题，请手动执行以下步骤

echo "========================================"
echo "ESP-ADF 手动安装指南"
echo "========================================"
echo ""
echo "由于网络限制，请按以下步骤手动安装："
echo ""
echo "步骤 1: 删除失败的目录"
echo "  rm -rf /Users/v/Desktop/esp32_demo/components/esp-adf"
echo ""
echo "步骤 2: 使用 Gitee 镜像克隆（国内用户推荐）"
echo "  cd /Users/v/Desktop/esp32_demo/components"
echo "  git clone --recursive https://gitee.com/EspressifSystems/esp-adf.git"
echo ""
echo "步骤 3: 等待子模块下载完成（可能需要10-30分钟）"
echo "  cd esp-adf"
echo "  git submodule update --init --recursive"
echo ""
echo "步骤 4: 验证安装"
echo "  ls components/esp-adf-libs/"
echo "  ls esp-idf/"
echo ""
echo "步骤 5: 更新 platformio.ini"
echo "  添加 lib_deps 或手动配置组件路径"
echo ""
echo "========================================"
