[env:esp32-s3-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

board_build.mcu = esp32s3
board_build.f_flash = 80000000L
board_build.flash_size = 8MB
board_build.flash_mode = qio

; 显式开启 PSRAM 支持 (Octal SPI / OPI PSRAM)
board_build.arduino.memory_type = qio_opi
board_build.partitions = default.csv

; ====== 音频框架配置 ======
board_build.core = esp32
board_build.language = en
board_build.exception = disabled

build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_ESP32_CAMERA_ENABLED=1
    -DCONFIG_SCCB_CLK_FREQ=100000
    -Wno-error
    -DCONFIG_HTTPD_MAX_URI_HANDLERS=128
    -DCONFIG_HTTPD_WS_SUPPORT=1
    ; FatFS 长文件名和中文编码支持
    -UCONFIG_FATFS_CODEPAGE
    -UCONFIG_FATFS_CODEPAGE_437
    -UCONFIG_FATFS_API_ENCODING_ANSI_OEM
    -DCONFIG_FATFS_CODEPAGE_936=1
    -DCONFIG_FATFS_CODEPAGE=936
    -DCONFIG_FATFS_API_ENCODING_UTF_8=1

build_unflags =
    -Werror
