[env:esp32-s3-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

board_build.mcu = esp32s3
board_build.f_flash = 80000000L
board_build.flash_mode = qio

; 显式开启 PSRAM 支持 (Octal SPI / OPI PSRAM)
board_build.arduino.memory_type = qio_opi
board_build.partitions = default.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_ESP32_CAMERA_ENABLED=1
    -DCONFIG_SCCB_CLK_FREQ=100000
    -Wno-error
    -DCONFIG_HTTPD_MAX_URI_HANDLERS=64
    -DCONFIG_HTTPD_WS_SUPPORT=1
build_unflags =
    -Werror