[env:esp32-s3-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.mcu = esp32s3
board_build.f_flash = 80000000L
board_build.flash_size = 8MB
board_build.flash_mode = qio

board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_build.data_dir = data/web
board_build.core = esp32
board_build.language = en
board_build.exception = disabled
board_build.filesystem = littlefs

; 移除阻断编译的全局硬性编译规则
build_unflags =
    -fuse-cxa-atexit
    -Wold-style-declaration

build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_ESP32_CAMERA_ENABLED=1
    -DCONFIG_SCCB_CLK_FREQ=100000
    -DCONFIG_HTTPD_MAX_URI_HANDLERS=256
    -DCONFIG_HTTPD_WS_SUPPORT=1
    -UCONFIG_FATFS_CODEPAGE
    -UCONFIG_FATFS_CODEPAGE_437
    -UCONFIG_FATFS_API_ENCODING_ANSI_OEM
    -DCONFIG_FATFS_CODEPAGE_936=1
    -DCONFIG_FATFS_CODEPAGE=936
    -DCONFIG_FATFS_API_ENCODING_UTF_8=1
    ; LittleFS Configuration
    -DCONFIG_LITTLEFS=y
    -DCONFIG_LITTLEFS_MAX_PARTITIONS=3
    -DCONFIG_LITTLEFS_PAGE_SIZE=256
    -DCONFIG_LITTLEFS_OBJ_NAME_LEN=64
    -DCONFIG_LITTLEFS_READ_SIZE=256
    -DCONFIG_LITTLEFS_WRITE_SIZE=256
    -DCONFIG_LITTLEFS_LOOKAHEAD_SIZE=128
    -DCONFIG_LITTLEFS_CACHE_SIZE=512
    -DCONFIG_LITTLEFS_BLOCK_CYCLES=512
    -DCONFIG_LITTLEFS_PARTITION_LABEL=\"webfs\"
    -DCONFIG_FS_MAX_FILE_NUM=16
    -Icomponents/esp_littlefs/include
    -Imanaged_components/espressif__cjson/include
    -I src/device/display
    -DLV_CONF_INCLUDE_SIMPLE
    -DCONFIG_USE_PSRAM=1
    -DCONFIG_SPIRAM_USE_MALLOC=1

    ; 核心解决：禁用此项警告的报错升格（针对 ESP-IDF 内部的 const static）
    -Wno-error=old-style-declaration
    -Wno-old-style-declaration
    -Wno-error=format=
    -Wno-error=shift-count-negative
    -Wno-error=unused-variable

lib_ldf_mode = chain+